### ISSUE TITLE
IPFS Gateway Timeout

### ISSUE THREAD

**Issue by Otto-AA** [fiatjaf/localfiles#1]
_(Not sure if this is caused by filemap.xyz or IPFS)_

When I try to open any file on the filemap it opens a link which (after trying to load for some time) resolves with a 504 Gateway Timeout result. I've tested it yesterday and now again with a file at King's Cross.

![IPFS Gateway Timeout](https://user-images.githubusercontent.com/21040751/44596459-85843080-a7cc-11e8-8319-8a8c2dee3319.png)

**Comment by fiatjaf** [comment]
When uploading a file you must make sure you keep the tap open until the file is pinned on IPFS.

But it seems that the pinning service on https://www.eternum.io/ is taking too long to pin the files, or to find them from the js-ipfs instance running on the browser.

I was trying to build this service without relying on a dedicated backend and without having to support direct file uploads, but apparently the architecture isn't solid enough.

To add insult to injury, I'm unable to build my own app again due to a bug in one of the subdependencies. I guess a lot will have to be rewritten from scratch. Is there anybody interested in grabbing this task?

**Comment by fiatjaf** [comment]
Ok, this thing doesn't use IPFS anymore, so this problem won't happen again.

**Comment by Otto-AA** [comment]
I guess it should be removed from [this list](https://github.com/ipfs/awesome-ipfs) then?

**Comment by fiatjaf** [comment]
Yes, it should.

**Comment by sergeevabc** [comment]
~Err… @fiatjaf, how long do you keep an uploaded file?~
Ah, it seems to be 3–4 days.
